name: tvbox-apk-sign

on:
  workflow_dispatch:
    inputs:
      rebuild:
      testOption:
        description: 'arm64支持，不支持ijk解码'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: chuckwxy
            repoName: TVBoxOSC
            branchName: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check New Commit
        run: |
          upStream=https://github.com/${{ matrix.userName }}/${{ matrix.repoName }}
          echo "upStream=$upStream" >> $GITHUB_ENV
          commit=$(curl -sL $upStream/commits/${{ matrix.branchName }} |grep -o "/${{ matrix.userName }}/${{ matrix.repoName }}/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
      - name: Checkout Source Code
        run: |
          git clone ${{ env.upStream }} TVBoxOSC
          cd TVBoxOSC
          git checkout ${{ env.commit }}
          echo "tag=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${{ env.commitS }} -1)" >> $GITHUB_ENV
      - name: Extra Modify
        working-directory: TVBoxOSC
        run: |
          echo '修改VersionName'
          sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'${{ env.tag }}\'#" app/build.gradle
          sed -i "/android:text=/s#=\"#=\"${{ env.tag }}\\\\n\\\\n#" app/src/main/res/layout/dialog_about.xml
          echo 'crosswalk源，防挂'
          if grep -q 'crosswalk' build.gradle; then
            sed -i "/crosswalk/a\        maven { url 'https://o0halflife0o.github.io/crosswalk/releases/crosswalk/android/maven2' }" build.gradle
          else
            sed -i "/jitpack.io/a\        maven { url 'https://o0halflife0o.github.io/crosswalk/releases/crosswalk/android/maven2' }" build.gradle
          fi
      - name: Compress Source Code
        working-directory: TVBoxOSC
        run: |
          #zip -q -x ".git/*" -x  ".github/*" -r source-${{ env.commitS }}.zip .
          tar -cJf source-${{ env.commitS }}.tar.xz --exclude=.git --exclude=.github *
      - name: Option For Test
        working-directory: TVBoxOSC
        run: |
          #添加arm64支持，不支持ijk解码
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" app/build.gradle
          sed -i "/armeabi-v7a[\'\"]$/s#\$#, 'arm64-v8a'#" player/build.gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build With Gradle
        working-directory: TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Download keystore.jks from private repo
        working-directory: TVBoxOSC
        env:   
           USERNAME: ${{ secrets.USERNAME }} 
           PASSWORD: ${{ secrets.PASSWORD }}  
        run: |  
          mkdir -p ./keystore  
          curl -s -o ./keystore/keystore.jks -L -u "$USERNAME:$PASSWORD" "https://github.com/chuckwxy/wxy/blob/main/keystore.jks"          
      - name: Sign APK
        working-directory: TVBoxOSC
        env:  
          KEYSTORE_PATH: ./keystore/keystore.jks 
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}  
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  
          SIGNING_KEY_ALIAS: myalias 
        run: |  
          echo "Signing APK with keystore password: $KEYSTORE_PASSWORD"  
          echo "Using key password: $KEY_PASSWORD"  
          ./gradlew signRelease  
      - name: Prepare App
        working-directory: TVBoxOSC
        run: |
          rm -rf apk/
          mkdir -p apk/
          for file in `find ~ -name "*release*.apk" -print`; do
            mv "$file" apk/TVBox_${{ matrix.userName }}_${{ env.tag }}.apk
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.userName }}-${{ matrix.repoName }}
          path: |
            TVBoxOSC/apk/*
